/* Generated by tools/build_content.py - do not edit by hand */
PNT.catalog = [
 {
  "id": "m01",
  "number": 1,
  "title": "PNT Fundamentals",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Explain what Positioning, Navigation and Timing mean as distinct capabilities.",
   "Distinguish PNT, GNSS and GPS correctly.",
   "Describe a simple end-to-end PNT chain from source to application.",
   "Recognise that a PNT capability may depend on upstream infrastructure, services and interfaces that are not visible to the consuming application.",
   "Explain why timing is fundamental both to GNSS positioning and to non-navigation systems.",
   "Distinguish accuracy, precision, integrity, availability and continuity.",
   "Identify different types of PNT dependency in an operational system.",
   "Explain why multiple GNSS constellations do not automatically create resilient PNT.",
   "Ask useful first-order engineering questions about a PNT-dependent system."
  ],
  "lessons": [
   {
    "id": "welcome-to-pnt-engineering",
    "title": "Welcome to PNT Engineering"
   },
   {
    "id": "what-is-pnt",
    "title": "What is PNT?"
   },
   {
    "id": "pnt-is-a-capability-not-a-single-technology",
    "title": "PNT is a Capability, not a Single Technology"
   },
   {
    "id": "gps-gnss-and-constellations",
    "title": "GPS, GNSS and Constellations"
   },
   {
    "id": "why-timing-matters-so-much",
    "title": "Why Timing Matters So Much"
   },
   {
    "id": "pnt-performance-accuracy-is-not-enough",
    "title": "PNT Performance: Accuracy is not Enough"
   },
   {
    "id": "understanding-pnt-dependency",
    "title": "Understanding PNT Dependency"
   },
   {
    "id": "the-first-resilience-lesson-diversity-is-not-independence",
    "title": "The First Resilience Lesson: Diversity is not Independence"
   },
   {
    "id": "speaking-like-a-pnt-engineer",
    "title": "Speaking Like a PNT Engineer"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 8
 },
 {
  "id": "m02",
  "number": 2,
  "title": "How GNSS Works",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Describe the basic GNSS system segments and the role of the user receiver.",
   "Explain why GNSS satellites broadcast both a ranging signal and navigation data.",
   "Explain, conceptually, how a receiver acquires and tracks satellite signals.",
   "Define pseudorange and explain why it is not the same as true geometric range.",
   "Explain the role of satellite clocks, receiver clock bias and time synchronisation.",
   "Distinguish ephemeris from almanac data.",
   "Explain how measurements from multiple satellites are combined to solve for Position, Velocity and Time.",
   "Recognise the importance of satellite geometry and coordinate/reference systems without needing to perform the mathematics.",
   "Explain why a coordinate is only meaningful when its reference frame, datum and height reference are understood.",
   "Describe the main processing chain inside a GNSS receiver at a system-engineering level."
  ],
  "lessons": [
   {
    "id": "from-pnt-capability-to-gnss-engineering",
    "title": "From PNT Capability to GNSS Engineering"
   },
   {
    "id": "the-gnss-system",
    "title": "The GNSS System"
   },
   {
    "id": "what-does-a-gnss-satellite-broadcast",
    "title": "What Does a GNSS Satellite Broadcast?"
   },
   {
    "id": "finding-a-satellite-acquisition-and-tracking",
    "title": "Finding a Satellite: Acquisition and Tracking"
   },
   {
    "id": "from-signal-travel-time-to-pseudorange",
    "title": "From Signal Travel Time to Pseudorange"
   },
   {
    "id": "clocks-the-hidden-core-of-gnss",
    "title": "Clocks: The Hidden Core of GNSS"
   },
   {
    "id": "ephemeris-and-almanac",
    "title": "Ephemeris and Almanac"
   },
   {
    "id": "where-is-the-satellite",
    "title": "Where is the Satellite?"
   },
   {
    "id": "solving-for-position-velocity-and-time",
    "title": "Solving for Position, Velocity and Time"
   },
   {
    "id": "a-receiver-is-a-processing-system",
    "title": "A Receiver is a Processing System"
   },
   {
    "id": "worked-conceptual-example",
    "title": "Worked Conceptual Example"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m03",
  "number": 3,
  "title": "GNSS Signals, Errors and Performance",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Identify the principal contributors to a GNSS pseudorange error budget.",
   "Explain why GNSS systems transmit multiple signals and frequencies, at a conceptual level.",
   "Describe ionospheric and tropospheric propagation effects and how they differ.",
   "Explain multipath, non-line-of-sight reception and signal obstruction.",
   "Recognise satellite orbit/clock, receiver and instrumental contributions to measurement error.",
   "Explain the difference between code pseudorange and carrier-phase measurements.",
   "Explain Dilution of Precision (DOP) and why geometry amplifies rather than creates measurement error.",
   "Distinguish GDOP, PDOP, HDOP, VDOP and TDOP at a practical level.",
   "Connect measurement quality and geometry to accuracy, availability, continuity and integrity.",
   "Ask meaningful engineering questions about claimed GNSS performance."
  ],
  "lessons": [
   {
    "id": "from-a-gnss-fix-to-a-trustworthy-gnss-fix",
    "title": "From a GNSS Fix to a Trustworthy GNSS Fix"
   },
   {
    "id": "the-gnss-measurement-error-budget",
    "title": "The GNSS Measurement Error Budget"
   },
   {
    "id": "gnss-signals-and-frequencies",
    "title": "GNSS Signals and Frequencies"
   },
   {
    "id": "the-ionosphere",
    "title": "The Ionosphere"
   },
   {
    "id": "the-troposphere",
    "title": "The Troposphere"
   },
   {
    "id": "multipath-nlos-and-obstruction",
    "title": "Multipath, NLOS and Obstruction"
   },
   {
    "id": "receiver-noise-and-equipment-effects",
    "title": "Receiver Noise and Equipment Effects"
   },
   {
    "id": "code-measurements-and-carrier-phase",
    "title": "Code Measurements and Carrier Phase"
   },
   {
    "id": "satellite-geometry-and-dilution-of-precision",
    "title": "Satellite Geometry and Dilution of Precision"
   },
   {
    "id": "why-vertical-accuracy-is-often-worse",
    "title": "Why Vertical Accuracy is Often Worse"
   },
   {
    "id": "measurement-quality-geometry-user-performance",
    "title": "Measurement Quality + Geometry = User Performance"
   },
   {
    "id": "reconnecting-to-pnt-performance",
    "title": "Reconnecting to PNT Performance"
   },
   {
    "id": "speaking-like-a-pnt-engineer",
    "title": "Speaking Like a PNT Engineer"
   },
   {
    "id": "worked-scenario-moving-from-open-sky-into-an-urban-canyon",
    "title": "Worked Scenario: Moving from Open Sky into an Urban Canyon"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m04",
  "number": 4,
  "title": "High-Accuracy and Augmented GNSS",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Explain the principle behind differential GNSS and why a known reference station is useful.",
   "Describe the role of correction data and why correction age, latency and distance can matter.",
   "Explain Satellite Based Augmentation Systems (SBAS) and distinguish their accuracy and integrity roles.",
   "Explain the basic principle of Real-Time Kinematic (RTK) positioning and why carrier-phase ambiguity resolution matters.",
   "Explain the basic principle of Precise Point Positioning (PPP) and how it differs from RTK.",
   "Recognise PPP-RTK as a hybrid family of approaches without treating terminology as universally identical across providers.",
   "Compare DGNSS, SBAS, RTK and PPP at a systems-engineering level.",
   "Explain why centimetre-level accuracy does not automatically imply resilience or integrity.",
   "Identify communications, infrastructure, coverage and convergence dependencies introduced by augmentation.",
   "Ask meaningful engineering and assurance questions about high-accuracy GNSS claims."
  ],
  "lessons": [
   {
    "id": "why-augment-gnss",
    "title": "Why Augment GNSS?"
   },
   {
    "id": "standalone-augmented-and-relative-positioning",
    "title": "Standalone, Augmented and Relative Positioning"
   },
   {
    "id": "differential-gnss-dgnss",
    "title": "Differential GNSS (DGNSS)"
   },
   {
    "id": "reference-stations-and-networks",
    "title": "Reference Stations and Networks"
   },
   {
    "id": "satellite-based-augmentation-systems-sbas",
    "title": "Satellite Based Augmentation Systems (SBAS)"
   },
   {
    "id": "real-time-kinematic-rtk",
    "title": "Real-Time Kinematic (RTK)"
   },
   {
    "id": "precise-point-positioning-ppp",
    "title": "Precise Point Positioning (PPP)"
   },
   {
    "id": "ppp-rtk-and-state-space-corrections",
    "title": "PPP-RTK and State-Space Corrections"
   },
   {
    "id": "comparing-the-main-approaches",
    "title": "Comparing the Main Approaches"
   },
   {
    "id": "communications-become-part-of-pnt",
    "title": "Communications Become Part of PNT"
   },
   {
    "id": "accuracy-is-not-integrity-and-accuracy-is-not-resilience",
    "title": "Accuracy is not Integrity, and Accuracy is not Resilience"
   },
   {
    "id": "engineering-selection-start-with-the-requirement",
    "title": "Engineering Selection: Start with the Requirement"
   },
   {
    "id": "worked-scenarios",
    "title": "Worked Scenarios"
   },
   {
    "id": "speaking-like-a-pnt-engineer",
    "title": "Speaking Like a PNT Engineer"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m05",
  "number": 5,
  "title": "Alternative PNT Technologies",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Explain the basic principles of inertial navigation and the role of accelerometers and gyroscopes.",
   "Explain dead reckoning and why its errors grow with time or distance.",
   "Describe odometry and other platform-derived navigation measurements.",
   "Explain clock holdover and distinguish frequency stability from absolute time knowledge.",
   "Distinguish time synchronisation from frequency synchronisation (syntonisation) and explain why distributing time is a separate engineering problem from generating or maintaining it.",
   "Recognise terrestrial radio-navigation and timing as alternatives or complements to GNSS.",
   "Explain the concept of signals of opportunity.",
   "Describe, at a high level, how network and telecommunications infrastructure can contribute to PNT.",
   "Explain why Low Earth Orbit (LEO) signals are being explored for PNT and distinguish opportunity from current maturity.",
   "Recognise visual, terrain, magnetic, celestial and emerging quantum techniques as alternative navigation sources.",
   "Describe how AI/ML may support PNT estimation, sensor management and anomaly detection, while recognising that performance and assurance must be demonstrated for the intended operating environment.",
   "Recognise lunar and cislunar PNT as an emerging application domain in which familiar PNT principles must be adapted to different reference, infrastructure and operational conditions.",
   "Evaluate alternative PNT sources in terms of independence, drift, coverage, infrastructure and common-mode failure."
  ],
  "lessons": [
   {
    "id": "pnt-does-not-begin-and-end-with-gnss",
    "title": "PNT Does Not Begin and End with GNSS"
   },
   {
    "id": "absolute-sources-and-relative-sources",
    "title": "Absolute Sources and Relative Sources"
   },
   {
    "id": "inertial-measurement-units-imus",
    "title": "Inertial Measurement Units (IMUs)"
   },
   {
    "id": "why-inertial-navigation-drifts",
    "title": "Why Inertial Navigation Drifts"
   },
   {
    "id": "dead-reckoning-and-odometry",
    "title": "Dead Reckoning and Odometry"
   },
   {
    "id": "sensor-fusion",
    "title": "Sensor Fusion"
   },
   {
    "id": "timing-without-continuous-gnss",
    "title": "Timing Without Continuous GNSS"
   },
   {
    "id": "terrestrial-radio-pnt-and-eloran",
    "title": "Terrestrial Radio PNT and eLoran"
   },
   {
    "id": "network-and-telecommunications-based-pnt",
    "title": "Network and Telecommunications-Based PNT"
   },
   {
    "id": "signals-of-opportunity",
    "title": "Signals of Opportunity"
   },
   {
    "id": "low-earth-orbit-leo-pnt",
    "title": "Low Earth Orbit (LEO) PNT"
   },
   {
    "id": "visual-and-image-based-navigation",
    "title": "Visual and Image-Based Navigation"
   },
   {
    "id": "terrain-celestial-and-magnetic-navigation",
    "title": "Terrain, Celestial and Magnetic Navigation"
   },
   {
    "id": "emerging-quantum-pnt",
    "title": "Emerging Quantum PNT"
   },
   {
    "id": "no-single-alternative-replaces-every-gnss-function",
    "title": "No Single Alternative Replaces Every GNSS Function"
   },
   {
    "id": "source-independence-and-common-mode-failure",
    "title": "Source Independence and Common-Mode Failure"
   },
   {
    "id": "worked-scenario-vehicle-enters-a-long-tunnel",
    "title": "Worked Scenario: Vehicle Enters a Long Tunnel"
   },
   {
    "id": "worked-scenario-timing-reference-is-lost",
    "title": "Worked Scenario: Timing Reference is Lost"
   },
   {
    "id": "speaking-like-a-pnt-engineer",
    "title": "Speaking Like a PNT Engineer"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m06",
  "number": 6,
  "title": "PNT Threats and Vulnerabilities",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Distinguish denial, degradation and deception of PNT services.",
   "Explain jamming at a systems-engineering level and why GNSS is susceptible to radio-frequency interference.",
   "Explain spoofing and distinguish it from ordinary measurement error.",
   "Explain meaconing as the rebroadcast or delay of legitimate navigation signals.",
   "Recognise accidental interference, equipment failure and environmental disruption as PNT threats.",
   "Explain how cyber and data-layer compromise can affect PNT without directly attacking the radio signal.",
   "Describe the effects of space weather on GNSS performance and availability.",
   "Identify common-mode vulnerabilities across nominally redundant PNT sources.",
   "Recognise observable indicators that may suggest PNT degradation or manipulation.",
   "Apply a risk lifecycle of identify, protect, detect, respond and recover to PNT-dependent systems.",
   "Distinguish threat, vulnerability, failure mechanism, harm and operational consequence when analysing PNT risk.",
   "Apply a complete-system threat model across source, signal/data, receiver, processing, interfaces, dependencies and consuming application.",
   "Recognise supply-chain and third-party service dependencies as part of the PNT attack and failure surface.",
   "Explain why threat attribution is secondary to timely detection of loss of PNT trust and safe operational response."
  ],
  "lessons": [
   {
    "id": "when-pnt-cannot-be-trusted",
    "title": "When PNT Cannot Be Trusted"
   },
   {
    "id": "threat-vulnerability-harm-and-mission-consequence",
    "title": "Threat, Vulnerability, Harm and Mission Consequence"
   },
   {
    "id": "three-useful-failure-states",
    "title": "Three Useful Failure States"
   },
   {
    "id": "why-gnss-signals-are-vulnerable-to-interference",
    "title": "Why GNSS Signals Are Vulnerable to Interference"
   },
   {
    "id": "jamming-denying-the-signal",
    "title": "Jamming: Denying the Signal"
   },
   {
    "id": "spoofing-deceiving-the-receiver",
    "title": "Spoofing: Deceiving the Receiver"
   },
   {
    "id": "meaconing-and-rebroadcast",
    "title": "Meaconing and Rebroadcast"
   },
   {
    "id": "accidental-rf-interference",
    "title": "Accidental RF Interference"
   },
   {
    "id": "cyber-and-data-layer-threats",
    "title": "Cyber and Data-Layer Threats"
   },
   {
    "id": "space-weather-and-natural-effects",
    "title": "Space Weather and Natural Effects"
   },
   {
    "id": "equipment-antenna-and-infrastructure-failure",
    "title": "Equipment, Antenna and Infrastructure Failure"
   },
   {
    "id": "common-mode-failure",
    "title": "Common-Mode Failure"
   },
   {
    "id": "supply-chain-and-third-party-dependencies",
    "title": "Supply Chain and Third-Party Dependencies"
   },
   {
    "id": "detecting-loss-of-trust",
    "title": "Detecting Loss of Trust"
   },
   {
    "id": "govern-identify-protect-detect-respond-recover",
    "title": "Govern, Identify, Protect, Detect, Respond, Recover"
   },
   {
    "id": "graceful-degradation",
    "title": "Graceful Degradation"
   },
   {
    "id": "threat-modelling-a-pnt-system",
    "title": "Threat Modelling a PNT System"
   },
   {
    "id": "worked-scenario-maritime-gnss-interference",
    "title": "Worked Scenario: Maritime GNSS Interference"
   },
   {
    "id": "worked-scenario-timing-attack-or-failure",
    "title": "Worked Scenario: Timing Attack or Failure"
   },
   {
    "id": "speaking-like-a-pnt-engineer",
    "title": "Speaking Like a PNT Engineer"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m07",
  "number": 7,
  "title": "Resilient PNT Engineering",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Distinguish redundancy, diversity, dissimilarity, independence, failover, holdover and recovery.",
   "Translate operational PNT needs into measurable resilience requirements.",
   "Explain resistance, detection, response and recovery as complementary resilience functions.",
   "Use recovery point and recovery time objectives to express mission-driven PNT recovery needs.",
   "Explain the functions of a layered resilient-PNT reference architecture.",
   "Understand source monitoring, fault detection, exclusion and isolation at a systems-engineering level.",
   "Explain why sensor fusion must be integrity-aware rather than simply combine every available source.",
   "Design normal, degraded, restricted, unavailable and recovery modes.",
   "Explain failover criteria, transition behaviour and the role of uncertainty during source loss.",
   "Explain why recovery requires revalidation rather than immediate reuse of a returning source.",
   "Identify hidden common-mode dependencies and single points of failure in apparently redundant architectures.",
   "Apply the architecture to navigation and timing failure scenarios and define appropriate evidence for assurance."
  ],
  "lessons": [
   {
    "id": "from-pnt-resilience-theory-to-engineering",
    "title": "From PNT Resilience Theory to Engineering"
   },
   {
    "id": "start-with-the-mission-not-the-technology",
    "title": "Start with the Mission, Not the Technology"
   },
   {
    "id": "redundancy-diversity-dissimilarity-and-independence",
    "title": "Redundancy, Diversity, Dissimilarity and Independence"
   },
   {
    "id": "defence-in-depth-for-pnt",
    "title": "Defence in Depth for PNT"
   },
   {
    "id": "source-monitoring-before-fusion",
    "title": "Source Monitoring Before Fusion"
   },
   {
    "id": "fault-detection-exclusion-and-isolation",
    "title": "Fault Detection, Exclusion and Isolation"
   },
   {
    "id": "worked-reference-architecture",
    "title": "Worked Reference Architecture"
   },
   {
    "id": "the-pnt-manager-and-state-machine",
    "title": "The PNT Manager and State Machine"
   },
   {
    "id": "failover-is-a-controlled-transition",
    "title": "Failover Is a Controlled Transition"
   },
   {
    "id": "hard-loss-scenario-gnss-disappears",
    "title": "Hard Loss Scenario: GNSS Disappears"
   },
   {
    "id": "deception-scenario-gnss-looks-healthy-but-becomes-suspect",
    "title": "Deception Scenario: GNSS Looks Healthy but Becomes Suspect"
   },
   {
    "id": "recovery-re-establishing-trust",
    "title": "Recovery: Re-establishing Trust"
   },
   {
    "id": "holdover-and-bridging-architectures",
    "title": "Holdover and Bridging Architectures"
   },
   {
    "id": "resilient-timing-architecture-example",
    "title": "Resilient Timing Architecture Example"
   },
   {
    "id": "avoiding-hidden-single-points-of-failure",
    "title": "Avoiding Hidden Single Points of Failure"
   },
   {
    "id": "sensor-fusion-for-resilience",
    "title": "Sensor Fusion for Resilience"
   },
   {
    "id": "designing-the-application-interface",
    "title": "Designing the Application Interface"
   },
   {
    "id": "engineering-evidence-and-testing",
    "title": "Engineering Evidence and Testing"
   },
   {
    "id": "architecture-review-checklist",
    "title": "Architecture Review Checklist"
   },
   {
    "id": "speaking-like-a-resilient-pnt-engineer",
    "title": "Speaking Like a Resilient-PNT Engineer"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m08",
  "number": 8,
  "title": "PNT Architecture and Systems Engineering",
  "subtitle": "",
  "version": "0.1",
  "objectives": [
   "Explain why PNT architecture should begin with mission and stakeholder needs rather than a preferred technology.",
   "Use user stories, use cases and operational scenarios to expose normal, degraded and failure behaviour.",
   "Identify PNT-dependent assets, stakeholders, external systems and system boundaries.",
   "Derive measurable functional, performance, resilience, interface, environmental and assurance requirements.",
   "Use accuracy, integrity, availability and continuity appropriately when specifying PNT performance.",
   "Express outage, holdover and recovery needs using time-bounded and mission-driven requirements.",
   "Allocate system-level requirements to PNT sources, monitoring, fusion, applications and supporting infrastructure.",
   "Develop functional, logical and physical views of a PNT architecture.",
   "Map the end-to-end PNT dependency chain, including external services, and identify hidden common-mode failure paths across a system of systems.",
   "Evaluate architecture options using traceable trade studies rather than selecting technology by headline accuracy.",
   "Maintain traceability from operational need through requirements, architecture and planned verification evidence.",
   "Recognise common PNT requirements and architecture anti-patterns."
  ],
  "lessons": [
   {
    "id": "from-resilient-components-to-an-engineered-pnt-system",
    "title": "From Resilient Components to an Engineered PNT System"
   },
   {
    "id": "the-systems-engineering-flow",
    "title": "The Systems-Engineering Flow"
   },
   {
    "id": "define-the-mission-and-stakeholders",
    "title": "Define the Mission and Stakeholders"
   },
   {
    "id": "user-stories-and-use-cases",
    "title": "User Stories and Use Cases"
   },
   {
    "id": "establish-the-system-boundary",
    "title": "Establish the System Boundary"
   },
   {
    "id": "map-the-pnt-dependency-chain-and-assets-at-risk",
    "title": "Map the PNT Dependency Chain and Assets at Risk"
   },
   {
    "id": "derive-requirements-from-operational-need",
    "title": "Derive Requirements from Operational Need"
   },
   {
    "id": "specify-the-pnt-performance-attributes",
    "title": "Specify the PNT Performance Attributes"
   },
   {
    "id": "resilience-requirements-threat-relative-and-time-bounded",
    "title": "Resilience Requirements: Threat-Relative and Time-Bounded"
   },
   {
    "id": "allocate-requirements-to-the-architecture",
    "title": "Allocate Requirements to the Architecture"
   },
   {
    "id": "functional-logical-and-physical-architecture-views",
    "title": "Functional, Logical and Physical Architecture Views"
   },
   {
    "id": "worked-architecture-exercise-resilient-autonomous-surface-pl",
    "title": "Worked Architecture Exercise: Resilient Autonomous Surface Platform"
   },
   {
    "id": "interface-engineering-pnt-is-more-than-coordinates",
    "title": "Interface Engineering: PNT Is More Than Coordinates"
   },
   {
    "id": "architecture-trade-studies",
    "title": "Architecture Trade Studies"
   },
   {
    "id": "traceability-and-the-pnt-requirements-matrix",
    "title": "Traceability and the PNT Requirements Matrix"
   },
   {
    "id": "architecture-and-requirements-anti-patterns",
    "title": "Architecture and Requirements Anti-Patterns"
   },
   {
    "id": "worked-mini-exercise-turn-a-vague-need-into-requirements",
    "title": "Worked Mini-Exercise: Turn a Vague Need into Requirements"
   },
   {
    "id": "speaking-like-a-pnt-systems-engineer",
    "title": "Speaking Like a PNT Systems Engineer"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m09",
  "number": 9,
  "title": "PNT Verification, Validation and Assurance",
  "subtitle": "Turning PNT requirements and resilience claims into objective evidence",
  "version": "0.1",
  "objectives": [
   "Distinguish verification, validation and assurance, and explain how they support different engineering decisions.",
   "Use Inspection, Analysis, Demonstration and Test (IADT) to select proportionate verification methods.",
   "Trace mission needs and PNT requirements to verification activities, acceptance criteria and retained evidence.",
   "Define suitable reference truth for position, velocity and timing measurements.",
   "Plan nominal, boundary, degraded, denial, deception, failover, holdover and recovery evaluation scenarios.",
   "Define measurable observables including error, uncertainty, availability, integrity state, detection time, failover time and recovery time.",
   "Explain why static and dynamic evaluation provide complementary evidence for resilient PNT.",
   "Use the PNT dependency chain to define verification scope and identify where evidence is required for external services, interfaces and shared dependencies.",
   "Assess coverage across threats, environments, configurations, sources, interfaces and operational modes.",
   "Recognise the importance of reproducibility, calibration, configuration control, logging and provenance.",
   "Build a simple PNT assurance argument linking claims to evidence, assumptions and residual risk.",
   "Challenge supplier test reports and resilience claims using evidence-led engineering questions."
  ],
  "lessons": [
   {
    "id": "from-engineering-claims-to-evidence",
    "title": "From Engineering Claims to Evidence"
   },
   {
    "id": "verification-validation-and-assurance-are-different",
    "title": "Verification, Validation and Assurance Are Different"
   },
   {
    "id": "the-requirements-to-evidence-chain",
    "title": "The Requirements-to-Evidence Chain"
   },
   {
    "id": "iadt-four-verification-methods",
    "title": "IADT: Four Verification Methods"
   },
   {
    "id": "start-with-testable-requirements",
    "title": "Start with Testable Requirements"
   },
   {
    "id": "define-reference-truth-before-measuring-error",
    "title": "Define Reference Truth Before Measuring Error"
   },
   {
    "id": "build-a-pnt-verification-matrix",
    "title": "Build a PNT Verification Matrix"
   },
   {
    "id": "test-environment-and-representativeness",
    "title": "Test Environment and Representativeness"
   },
   {
    "id": "nominal-performance-is-only-the-baseline",
    "title": "Nominal Performance Is Only the Baseline"
   },
   {
    "id": "resilience-testing-exercise-the-failure-behaviour",
    "title": "Resilience Testing: Exercise the Failure Behaviour"
   },
   {
    "id": "detection-performance-needs-its-own-metrics",
    "title": "Detection Performance Needs Its Own Metrics"
   },
   {
    "id": "holdover-and-bridging-tests",
    "title": "Holdover and Bridging Tests"
   },
   {
    "id": "recovery-testing-is-more-than-restoring-the-source",
    "title": "Recovery Testing Is More Than Restoring the Source"
   },
   {
    "id": "negative-boundary-and-fault-injection-testing",
    "title": "Negative, Boundary and Fault-Injection Testing"
   },
   {
    "id": "static-evaluation-inspect-what-dynamic-tests-cannot-prove",
    "title": "Static Evaluation: Inspect What Dynamic Tests Cannot Prove"
   },
   {
    "id": "coverage-how-much-evidence-is-enough",
    "title": "Coverage: How Much Evidence Is Enough?"
   },
   {
    "id": "reproducibility-configuration-and-evidence-quality",
    "title": "Reproducibility, Configuration and Evidence Quality"
   },
   {
    "id": "worked-example-assuring-the-module-8-surface-platform",
    "title": "Worked Example: Assuring the Module 8 Surface Platform"
   },
   {
    "id": "worked-example-misleading-gnss-and-failover",
    "title": "Worked Example: Misleading GNSS and Failover"
   },
   {
    "id": "building-a-pnt-assurance-case",
    "title": "Building a PNT Assurance Case"
   },
   {
    "id": "challenging-supplier-evidence",
    "title": "Challenging Supplier Evidence"
   },
   {
    "id": "common-assurance-anti-patterns",
    "title": "Common Assurance Anti-Patterns"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning",
    "title": "Further Learning"
   },
   {
    "id": "next-module",
    "title": "Next Module"
   }
  ],
  "practiceCount": 10
 },
 {
  "id": "m10",
  "number": 10,
  "title": "Applied PNT Engineering (Capstone)",
  "subtitle": "Capstone: From mission need to an assured PNT solution",
  "version": "0.1",
  "objectives": [
   "Frame an operational problem in terms of Positioning, Navigation and Timing rather than immediately selecting technology.",
   "Identify mission-critical PNT capabilities, consumers, dependencies, interfaces and consequences of loss or deception.",
   "Trace the end-to-end PNT dependency chain, including upstream infrastructure and downstream consumers that may sit outside the immediate system boundary.",
   "Derive measurable performance and resilience requirements from operational scenarios.",
   "Construct a threat and common-mode analysis appropriate to the system boundary and environment.",
   "Develop and justify a multi-source resilient PNT architecture.",
   "Define normal, degraded, restricted, failover, holdover and recovery behaviours.",
   "Select suitable verification methods, reference truth, observables and acceptance criteria.",
   "Build a concise assurance argument that links claims to evidence, assumptions and residual risks.",
   "Communicate PNT engineering decisions clearly to technical and non-technical stakeholders.",
   "Challenge apparently attractive solutions that do not trace back to mission need or independently evidenced requirements.",
   "Evaluate emerging or supplier-proposed PNT technologies using evidence of maturity, operating envelope, integration dependencies and assurance rather than novelty or headline claims."
  ],
  "lessons": [
   {
    "id": "the-capstone-think-like-a-pnt-engineer",
    "title": "The Capstone: Think Like a PNT Engineer"
   },
   {
    "id": "a-repeatable-applied-pnt-engineering-method",
    "title": "A Repeatable Applied PNT Engineering Method"
   },
   {
    "id": "worked-case-study-autonomous-coastal-surveillance-craft",
    "title": "Worked Case Study: Autonomous Coastal Surveillance Craft"
   },
   {
    "id": "deriving-requirements-from-the-scenario",
    "title": "Deriving Requirements from the Scenario"
   },
   {
    "id": "threat-and-common-mode-analysis",
    "title": "Threat and Common-Mode Analysis"
   },
   {
    "id": "candidate-resilient-architecture",
    "title": "Candidate Resilient Architecture"
   },
   {
    "id": "walkthrough-hard-gnss-loss",
    "title": "Walkthrough: Hard GNSS Loss"
   },
   {
    "id": "walkthrough-plausible-but-wrong-gnss",
    "title": "Walkthrough: Plausible but Wrong GNSS"
   },
   {
    "id": "turning-the-design-into-verification-evidence",
    "title": "Turning the Design into Verification Evidence"
   },
   {
    "id": "from-evidence-to-a-pnt-assurance-argument",
    "title": "From Evidence to a PNT Assurance Argument"
   },
   {
    "id": "design-review-questions-an-sme-should-ask",
    "title": "Design Review: Questions an SME Should Ask"
   },
   {
    "id": "common-capstone-failure-modes",
    "title": "Common Capstone Failure Modes"
   },
   {
    "id": "emerging-technology-evidence-challenge",
    "title": "Emerging Technology Evidence Challenge"
   },
   {
    "id": "learner-capstone-exercise",
    "title": "Learner Capstone Exercise"
   },
   {
    "id": "capstone-assessment-rubric",
    "title": "Capstone Assessment Rubric"
   },
   {
    "id": "module-summary",
    "title": "Module Summary"
   },
   {
    "id": "key-terms",
    "title": "Key Terms"
   },
   {
    "id": "further-learning-and-source-material",
    "title": "Further Learning and Source Material"
   },
   {
    "id": "programme-completion-and-next-step",
    "title": "Programme Completion and Next Step"
   }
  ],
  "practiceCount": 10
 }
];
